process.env.DD_PROFILING_EXPERIMENTAL_CPU_ENABLED = "true";
process.env["DD_PROFILING_EXPERIMENTAL_TIMELINE_ENABLED"] = "false";

const env = {
  DD_PROFILING_EXPERIMENTAL_CODEHOTSPOTS_ENABLED: "true",
  "DD_PROFILING_EXPERIMENTAL_ENDPOINT_COLLECTION_ENABLED": "true",
  UNRELATED: "DD_PROFILING_EXPERIMENTAL_CPU_ENABLED"
};
