process.env.DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED = "true";
process.env["DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED"] = "false";

const env = {
  DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED: "true",
  UNRELATED: "DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED"
};
